# Generated by Django 6.0.5 on 2026-05-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Име на категория')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='URL slug')),
                ('icon', models.CharField(default='🔧', max_length=50, verbose_name='Икона/емоджи')),
                ('meta_title', models.CharField(max_length=60, verbose_name='SEO заглавие (Title)')),
                ('meta_description', models.CharField(max_length=160, verbose_name='SEO описание (Meta Description)')),
                ('h1_title', models.CharField(max_length=100, verbose_name='H1 заглавие')),
                ('description', models.TextField(verbose_name='Описание на категорията')),
                ('keywords', models.CharField(blank=True, max_length=255, verbose_name='Ключови думи')),
                ('seo_content', models.TextField(blank=True, verbose_name='Допълнително SEO съдържание')),
                ('professionals_count', models.IntegerField(default=0, verbose_name='Брой майстори')),
                ('average_rating', models.DecimalField(decimal_places=2, default=4.5, max_digits=3, verbose_name='Среден рейтинг')),
                ('completed_jobs', models.IntegerField(default=0, verbose_name='Завършени проекти')),
                ('order', models.IntegerField(default=0, verbose_name='Ред на показване')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order', 'name'],
            },
        ),
    ]
