# Generated by Django 6.0.5 on 2026-05-26 22:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/clients/', verbose_name='Снимка')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='За мен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенти',
            },
        ),
        migrations.CreateModel(
            name='ProfessionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заглавие на профила')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='URL slug')),
                ('description', models.TextField(max_length=2000, validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='Описание')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Имейл')),
                ('website', models.URLField(blank=True, verbose_name='Уебсайт')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Град')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен профил')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Верифициран')),
                ('views_count', models.IntegerField(default=0, verbose_name='Брой прегледи')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Рейтинг')),
                ('reviews_count', models.IntegerField(default=0, verbose_name='Брой отзиви')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(related_name='professionals', to='core.category', verbose_name='Категории услуги')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Професионалист',
                'verbose_name_plural': 'Професионалисти',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='professionals/images/', verbose_name='Снимка')),
                ('caption', models.CharField(blank=True, max_length=250, validators=[django.core.validators.MaxLengthValidator(250)], verbose_name='Описание')),
                ('order', models.IntegerField(default=0, verbose_name='Ред на показване')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.professionalprofile', verbose_name='Професионалист')),
            ],
            options={
                'verbose_name': 'Снимка на професионалист',
                'verbose_name_plural': 'Снимки на професионалисти',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
