# Generated by Django 6.0.5 on 2026-05-26 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_clientprofile_professionalprofile_professionalimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='phone',
        ),
    ]
