# Generated by Django 6.0.5 on 2026-06-01 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_clientprofile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Име на града')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='URL slug')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Област')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.IntegerField(default=0, verbose_name='Ред на показване')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Град',
                'verbose_name_plural': 'Градове',
                'ordering': ['order', 'name'],
            },
        ),
    ]
