# Generated by Django 6.0.5 on 2026-08-03 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalprofile',
            name='phone',
        ),
    ]
