# Generated by Django 6.0.5 on 2026-08-03 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_professionalprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
    ]
